### ISSUE TITLE
Use the main domain as XMPP server

### ISSUE THREAD

**Issue by s0r00t** [YunoHost-Apps/jappix_ynh#15]
If using a subdomain (ex: pix.domain.tld), Jappix will try to use it as XMPP server (ex: vjud.pix.domain.tld).

The main domain will (if not always) often be the XMPP server.
Another solution would be to ask for the XMPP server @ installation, and with default choice the main domain.

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/503

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)
